---
- name: detect latest chisel release
  github_release:
    repository: jpillora/chisel
    release: "{{ srv_chisel_version }}"
    strip_v: true
    template: '{download_url}/chisel_{ver}_linux_amd64.gz'
    creates: "{{ srv_chisel_binary }}"
    reinstall: "{{ srv_chisel_upgrade |bool }}"
  tags: skip_ansible_lint
  register: latest_chisel_release

- name: download compressed chisel binary
  get_url:
    url: "{{ latest_chisel_release.url }}"
    dest: "{{ srv_chisel_binary }}.gz"
    mode: 0755
    force: true
  when: latest_chisel_release is changed
  register: get_chisel_result

- name: uncompress chisel binary
  command: gunzip -f "{{ srv_chisel_binary }}.gz"
  when: get_chisel_result is changed
...
